services:
  - type: web
    name: react-seed
    runtime: static
    buildCommand: cd seed && npm ci --include=dev && npm run build:render
    staticPublishPath: seed/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeployTrigger: commit
