services:
  - type: web
    name: react-seed-app
    env: node
    buildCommand: npm run build:all
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 