services:
  - type: web
    name: server-koa
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Ensure data directory is included in deployment
    include:
      - server-koa/data/**
    healthCheckPath: /
    autoDeploy: true 