services:
  - type: web
    name: react-seed-app
    env: node
    buildCommand: |
      npm install
      cd server-koa && npm install
      cd ..
      npm run build:all
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true 